// Generated by CoffeeScript 1.6.3
var file, path, reviewStatus, reviewStatuses, visible, _ref;

reviewStatuses = JSON.parse(localStorage.githubPRReview || '{}');

$('div.meta').on('click', function() {
  var hiddenComment;
  hiddenComment = $(this).siblings('div.data').toggle();
  reviewStatuses[window.location.pathname + '|' + $(this).attr('data-path')] = hiddenComment.is(':visible');
  return localStorage.githubPRReview = JSON.stringify(reviewStatuses);
});

for (reviewStatus in reviewStatuses) {
  visible = reviewStatuses[reviewStatus];
  _ref = reviewStatus.split('|'), path = _ref[0], file = _ref[1];
  if (path !== location.pathname) {
    continue;
  }
  if (!visible) {
    $('div.meta:contains(' + file + ')').siblings('div.data').hide();
  }
}
